# Generated by Django 5.1.4 on 2024-12-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0004_alter_category_created_at_alter_category_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
    ]
